name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We value community input on making NobleOne better.

  - type: dropdown
    id: component
    attributes:
      label: Target Component
      description: Which part of the system would this feature affect?
      options:
        - Driver Interface (Touch screen UI)
        - Fleet Management (Manager dashboard)
        - Hardware Integration (CAN bus, sensors)
        - Installation/Setup
        - API/Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: Who would primarily benefit from this feature?
      options:
        - Forklift Operators/Drivers
        - Fleet Managers
        - System Administrators
        - Maintenance Technicians
        - End Customers
        - Developers/Integrators
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the current pain point or limitation
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative approaches you've considered?
      placeholder: Other ways this could be solved

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this feature to your operations?
      options:
        - Critical - Blocking adoption/usage
        - High - Significant operational benefit
        - Medium - Nice to have improvement
        - Low - Minor convenience
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Feature Scope
      description: Check all that apply
      options:
        - label: Real-time operation critical
        - label: Offline capability needed
        - label: Multi-truck coordination
        - label: Safety/compliance related
        - label: Performance optimization
        - label: User experience improvement
        - label: Integration with external systems

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How would you know this feature is working correctly?
      placeholder: |
        - Should be able to...
        - Must support...
        - Should display...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, references, etc.
      placeholder: Links to similar features, screenshots, business requirements