name: Installation Support
description: Get help with installation or setup issues
title: "[INSTALL] "
labels: ["support", "installation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Need help with installation? Please provide details about your setup and what's not working.

  - type: dropdown
    id: install_type
    attributes:
      label: Installation Type
      description: What type of installation are you attempting?
      options:
        - Fresh installation (new system)
        - Upgrade from previous version
        - Reinstallation (fixing broken system)
        - Development setup
        - Custom/modified installation
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Target Hardware
      description: What hardware are you installing on?
      options:
        - Personal Computer (Hub UI)
        - Nvidia Jetson Orin Nano
        - Nvidia Jetson AGX
        - Nvidia Jetson Thor
        - Other/Unknown
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS version are you using?
      placeholder: "e.g., Ubuntu 22.04 LTS, JetPack 6.0"
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Installation Method
      description: How are you installing NobleOne?
      options:
        - Using install.sh script (recommended)
        - Manual installation
        - Docker containers only
        - Development build from source
        - Other method
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Installation Issue
      description: What's going wrong with the installation?
      placeholder: Describe the problem you're encountering
    validations:
      required: true

  - type: textarea
    id: steps_taken
    attributes:
      label: Steps Already Tried
      description: What have you already attempted?
      placeholder: |
        1. Downloaded install.sh
        2. Ran sudo ./install.sh
        3. Got error at step X

  - type: textarea
    id: error_output
    attributes:
      label: Error Output
      description: Complete error messages or log output
      placeholder: Paste the full error message or log output here
      render: shell

  - type: checkboxes
    id: requirements
    attributes:
      label: System Requirements Check
      description: Verify your system meets requirements
      options:
        - label: Internet connection available
        - label: Sufficient disk space (>8GB free)
        - label: Root/sudo access available
        - label: Hardware supports Docker
        - label: No conflicting software installed

  - type: dropdown
    id: network
    attributes:
      label: Network Environment
      description: What's your network setup?
      options:
        - Standard internet connection
        - Corporate/restricted network
        - Offline/air-gapped installation
        - Behind proxy/firewall
        - Other configuration

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might help
      placeholder: Special requirements, network restrictions, custom configurations, etc.